# Generated by Django 5.2.7 on 2025-11-03 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classification', models.CharField(default='CLASSIFIED', help_text='e.g., CLASSIFIED, CONFIDENTIAL', max_length=50)),
                ('description', models.TextField()),
                ('role', models.CharField(blank=True, help_text='e.g., Security Consultant, Developer', max_length=200)),
                ('specializations', models.CharField(blank=True, help_text='Comma-separated list', max_length=500)),
                ('contact_info', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main.partner')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
