# Generated by Django 5.2.7 on 2025-11-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_partner_partnerdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='role',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='specializations',
        ),
        migrations.AddField(
            model_name='partner',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='agents/'),
        ),
        migrations.DeleteModel(
            name='PartnerDetail',
        ),
    ]
