# Generated by Django 5.2.7 on 2025-11-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_partner_options_remove_partner_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='specifications',
            field=models.TextField(blank=True, help_text='Project specifications or technical details'),
        ),
        migrations.AddField(
            model_name='project',
            name='white_paper',
            field=models.FileField(blank=True, help_text='PDF, DOCX, or other document file', null=True, upload_to='projects/whitepapers/'),
        ),
    ]
