"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import Config, RepositoryEnv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .secret/.env
SECRET_ENV_FILE = BASE_DIR / '.secret' / '.env'
if SECRET_ENV_FILE.exists():
    config = Config(RepositoryEnv(str(SECRET_ENV_FILE)))
else:
    # Fallback to os.getenv if .secret/.env doesn't exist
    config = None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEFAULT_SECRET_KEY = 'django-insecure-)jjir%n7dbtija70%o0cc9q8ocjvl-s(pjafj50$danridnq-('
if config:
    SECRET_KEY = config('SECRET_KEY', default=DEFAULT_SECRET_KEY)
else:
    SECRET_KEY = os.getenv('SECRET_KEY', DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

# Server Configuration
# Port and host can be overridden via environment variables:
#   export DJANGO_PORT=9444
#   export DJANGO_HOST=0.0.0.0
# Access in code: from django.conf import settings; settings.SERVER_PORT
def get_env(key, default=None, cast=None):
    """Get environment variable from .secret/.env or system environment"""
    if config:
        if cast is not None:
            return config(key, default=default, cast=cast)
        else:
            return config(key, default=default)
    value = os.getenv(key, default)
    if cast and value:
        return cast(value)
    return value

SERVER_PORT = int(get_env('DJANGO_PORT', 9441))
SERVER_HOST = get_env('DJANGO_HOST', '0.0.0.0')

# Web3 Payment Configuration
WALLET_ADDRESS = get_env('WALLET_ADDRESS', '0x0000000000000000000000000000000000000000')
RPC_URL = get_env('RPC_URL', 'https://mainnet.infura.io/v3/YOUR_PROJECT_ID')
CHAIN_ID = int(get_env('CHAIN_ID', 1))  # 1 for Ethereum mainnet, 5 for Goerli testnet
PAYMENT_AMOUNT_ETH = float(get_env('PAYMENT_AMOUNT_ETH', 0.02))  # Default 0.02 ETH
PAYMENT_EXPIRY_HOURS = int(get_env('PAYMENT_EXPIRY_HOURS', 24))  # Download link valid for 24 hours


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'frontend' / 'build' / 'static',  # React build static files
]

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
